name: guess
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.10
  - numpy=1.23.*
  - scipy
  - matplotlib
  - xarray
  - netcdf4
  - pandas
  - pyyaml
  - pytest
  - pip
  - pyproj
  - jupyter
  - jupyterlab
  - cartopy
  - tqdm
  - sphinx
  - numba
  - imbalanced-learn
  - pyarrow
  - properscoring
  - pip:
    - tensorflow[and-cuda]
    - echo-opt
    - hagelslag
    - bridgescaler
    - git+https://github.com/ai2es/ptype-physical.git
    - .
