name: guesstorch
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11
  - numpy<2
  - scipy
  - matplotlib
  - xarray
  - metpy
  - netcdf4
  - pandas
  - pyyaml
  - pytest
  - pip
  - pyproj
  - jupyter
  - jupyterlab
  - cartopy
  - tqdm
  - seaborn
  - sphinx
  - numba
  - properscoring
  - pyarrow
  - imbalanced-learn
  - pytorch
  - pytorch-cuda=12.1
  - pip:
    - keras
    - echo-opt
    - hagelslag
    - bridgescaler
    - safetensors
    - -e .
