name: guess
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy<1.24
  - scipy
  - matplotlib
  - xarray
  - netcdf4
  - pandas
  - pyyaml
  - pytest
  - pip
  - pyproj
  - jupyter
  - jupyterlab
  - cartopy
  - tqdm
  - sphinx
  - numba
  - properscoring
  - pyarrow
  - imbalanced-learn
  - pip:
    - tensorflow
    - tensorflow_addons
    - echo-opt
    - hagelslag
    - bridgescaler
    - git+https://github.com/ai2es/ptype-physical.git
    - .
