name: guesstf
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - numpy<2
  - scipy
  - matplotlib
  - xarray
  - metpy
  - netcdf4
  - pandas
  - pyyaml
  - pytest
  - pip
  - pyproj
  - jupyter
  - jupyterlab
  - cartopy
  - tqdm
  - seaborn
  - sphinx
  - numba
  - properscoring
  - pyarrow
  - imbalanced-learn
  - pip:
    - tensorflow[and-cuda]
    - keras
    - echo-opt
    - hagelslag
    - bridgescaler
    - -e git+https://github.com/ai2es/ptype-physical.git#egg=ptype
    - -e .
