pbs:
  name: ev-trainer
  select: 1
  ncpus: 8
  ngpus: 1
  mem: 128GB
  walltime: 24:00:00
  gpu_type: v100
  account: NAML0001
  queue: casper
  env_setup: |
    source ~/.bashrc
    ncar_pylib /glade/work/$USER/py37